name: diff_tgv_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scikit-image
  - sporco
  - tqdm
  - ninja
  - pytorch::pytorch
  - pytorch::torchvision
  - tensorboard
  - pip:
      - ml_collections
      - ninja
